dist: xenial

language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -r requirements-site.txt

script: 
  - yarn test
  - yarn site

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  
  - provider: pages
    local_dir: site
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master

  - provider: script
    script: ./scripts/docker.sh
    on:
      branch: master
