dist: xenial

language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script: 
  - yarn test

notifications:
  email:
    on_success: change
    on_failure: change

deploy:

  - provider: script
    script: yarn site
    on:
      tags: true
  
  - provider: pages
    local_dir: site
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      tags: true

  - provider: script
    script: ./scripts/docker.sh
    on:
      tags: true

  - provider: script
    script: ./scripts/pypi.sh
    on:
      tags: true
