dist: xenial

language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script: 
  - yarn test

notifications:
  email:
    on_success: change
    on_failure: change

deploy:

  - provider: script
    script: yarn site
    on:
      tags: true
  
  - provider: pages
    local_dir: site
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      tags: true

  - provider: script
    script: make package
    on:
      tags: true

  - provider: script
    script: ./scripts/docker.sh
    on:
      tags: true

  - provider: pypi
    user: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
      tags: true

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - dist/termlink-*-py2-none-any.whl
      - dist/termlink-*.tar.gz
    on:
      tags: true
