name: Release

on:
  push:
    tags:
      - v*

jobs:
  Release:
    if: ${{ github.head_ref }} == "master"
    runs-on: ubuntu-latest
    environment: pypi
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install twine wheel
        pip install -r requirements.txt
    - name: Package
      run: |
        make package
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.LIFEOMIC_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.LIFEOMIC_PYPI_TOKEN }}
      run: |
        make deploy
