# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validate Pull Request

on: [ pull_request ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
        
